# Generated by Django 2.1.5 on 2020-04-01 17:06

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='images/users/default.jpg', upload_to='images/users/'),
        ),
    ]
