# Generated by Django 2.1.5 on 2020-03-31 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreport',
            name='content',
        ),
    ]
